language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
before_script:
  - rustup component add clippy rustfmt
script:
  - cargo fmt --all -- --check
  - cargo clippy -- -D warnings
  - cargo test
