[package]
name = "kube-conf"
version = "0.1.0"
authors = ["Espen Henriksen <dev@henriksen.is>"]
edition = "2018"

[dependencies]
serde = "1.0.90"
serde_yaml = "0.8.8"
error-chain = "0.12.0"
serde_derive = "1.0.90"
